### ISSUE TITLE
Diffrent Results between Klippers Shaper Calibration and Klippain on X Axis

### ISSUE THREAD

**Issue by NightHammer1000** [Frix-x/klippain-shaketune#107]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v3.0.0

### Describe the bug and expected behavior

Running the Klippers own Shaper Calibration gives me widely different results then using Klippain.

Built In Suggests:

The Results for X is this:
![shaper_calibrate_x](https://github.com/Frix-x/klippain-shaketune/assets/1979250/214d00a9-2c48-4422-99e8-75dd03be81f4)

While Klippain gives me this:
![shaper_20240517_094423_X](https://github.com/Frix-x/klippain-shaketune/assets/1979250/bbcdcc74-b6c9-484f-92a6-b23f8915d404)

Somehow, the Peaks are flipped in Klippain. The Klipper built in Results gives much better Print Quality too.

Y, on the other hand, seems Identical. Even tho, Klippain suggests other settings than Built-in:
Built In:
![shaper_calibrate_y](https://github.com/Frix-x/klippain-shaketune/assets/1979250/9e53e8b5-2016-4f46-8d3c-b70af674662c)

Kliappain:
![shaper_20240517_094654_Y](https://github.com/Frix-x/klippain-shaketune/assets/1979250/71394082-7f6d-484b-b969-e97e2d68062b)

The printer is a QIDI X-PLUS set up from scratch with Upstream Klipper.

**Comment by Frix-x** [comment]
Hello!

This seems a little strange to me. Are you sure it is reproducible?
Actually it's a bit strange to me because my macros call the original Klipper TEST_RESONANCE under the hood, so all the measurement part is done directly by Klipper. Shake&Tune is then based on the original plotting script, but with added insights. This means that there should be no difference in the recorded signal, only in the cosmetic elements added to it (like peak detection, etc...).

**Comment by NightHammer1000** [comment]
Yep. It is reproducable. Again and again.
The Peaks are always flipped.

Did 3 runs right now. All 3 have the same result.
