### ISSUE TITLE
Error after running belt or input shaper calibration

### ISSUE THREAD

**Issue by drumstick77** [Frix-x/klippain-shaketune#108]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v3.0.0-0-g47770e2d

### Describe the bug and expected behavior

![image](https://github.com/Frix-x/klippain-shaketune/assets/1726110/a8a21e9c-2a9c-49ba-a570-4bd18a415e74)

Hi all, please see screenshot. getting that after running either belt of shaper calibration. it ran okay but always got that message and normally the CSV files get deleted automatically but they don't.

I've re-installed this but still getting same error. any thoughts please? Thanks

**Comment by Frix-x** [comment]
Hello, you seems to use an outdated version of S&T as this issue was solved in the commit https://github.com/Frix-x/klippain-shaketune/commit/56a5502d81a9071b1a40f5da4138f195eb6bf8ec from 3 weeks ago. You need to have v3.0.0-1.

If you don't see it, check your moonraker.conf to get the correct configuration. A template can be found here: https://github.com/Frix-x/klippain-shaketune/blob/main/moonraker.conf
