### ISSUE TITLE
Dependency conflict with dangerklipper

### ISSUE THREAD

**Issue by Laikulo** [Frix-x/klippain-shaketune#135]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

N/A

### Describe the bug and expected behavior

Both `main` and `develop` explicty specify `numpy==1.26.2`, but dangerklipper currently specifies `numpy==1.25.2`
https://github.com/DangerKlippers/danger-klipper/blob/8adfaeb9b6289e5421f2095a3f48c24d06a55305/scripts/klippy-requirements.txt#L12C1-L12C14

### Additional information and klippy.log

This was found while cooking up some smoke tests, and the dangerklipper tests died because of this.
https://github.com/Laikulo/shaketune/actions/runs/9688597940/job/26735455067

```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

The conflict is caused by:
    The user requested numpy==1.25.2
    The user requested numpy==1.26.2
```

**Comment by Frix-x** [comment]
Hello,

I had a lot of problems with the spectrograms in the past due to a memory problem using the older numpy lib and it was solved by switching to this version and also using Scipy instead of mplotlib.specgram(). But I'm pretty sure that DK only uses numpy in its requirements to pre-install the resonance testing stuff, so it should be no problem to replace it with numpy=1.26.2, which is needed by Shake&Tune.

If you think this is a problem, I can try using 1.25.2 again and see how it goes... Maybe Scipy alone was enough to fix the problem?

But thanks for raising this issue, I'm just unsure if I need to solve it and what is the best strategy to do so ^^
