### ISSUE TITLE
ValueError: array is too big

### ISSUE THREAD

**Issue by Killajoedotcom** [Frix-x/klippain-shaketune#62]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.5.0-7-gb42e377a

### Describe the bug and expected behavior

I saw that this was an issue before, but after installing Shake&Tune a couple of days ago, I'm getting the "ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size." issue.

I'd appreciate any help someone could provide.

### Additional information and klippy.log

[klippy.log](https://github.com/Frix-x/klippain-shaketune/files/14225782/klippy.log)

**Comment by Frix-x** [comment]
Ok, I see that you are using the full Klippain config. So it's normal since in Klippain it's a custom S&T v1.x that is included. But this will change with the next Klippain version where all the things were done in order to support the standard and classic S&T. So please be a bit patient, the next version is planned very soon :)
