### ISSUE TITLE
AXES_SHAPER_CALIBRATION doesn't generate graph

### ISSUE THREAD

**Issue by Phil1988** [Frix-x/klippain-shaketune#86]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.6.0-3

### Describe the bug and expected behavior

I just installed latest klipper and updated S&T.
First I had a problem with scipy when doing the `AXES_SHAPER_CALIBRATION` on the latest v2.6.1-0 of S&T, so I went down to v2.6.0-3.
It gave this errors:
![image](https://github.com/Frix-x/klippain-shaketune/assets/6054234/685e9799-217e-45fc-ada2-32b71c230c3d)

Installing S&T again via
`wget -O - https://raw.githubusercontent.com/Frix-x/klippain-shaketune/main/install.sh | bash`
installed scipy etc. and the `AXES_SHAPER_CALIBRATION` works now.

Started the `VIBRATIONS_CALIBRATION` and it gave me these errors:
![image](https://github.com/Frix-x/klippain-shaketune/assets/6054234/94cd8949-6116-4eb4-b261-6b2dbc737a32)

I have no idea whats the cause and how I can solve it.

**Comment by Phil1988** [comment]
Ok, so there have been recently changes in klipper, that deprecated the `max_accel_to_decel `parameter (see here https://www.klipper3d.org/Config_Reference.html#printer and here: https://www.klipper3d.org/Config_Changes.html)
![image](https://github.com/Frix-x/klippain-shaketune/assets/6054234/9b54f5e5-5e6e-407c-aa0c-f9ed6f321b81)


This cause the` VIBRATIONS_CALIBRATION ` macro to give that error because of line 28:
` {% set old_accel_to_decel = printer.toolhead.max_accel_to_decel %}`

and at line 164:
`SET_VELOCITY_LIMIT ACCEL={old_accel} ACCEL_TO_DECEL={old_accel_to_decel} SQUARE_CORNER_VELOCITY={old_sqv}`

Solution is to delete line 28 and to modify line 164 to:
`SET_VELOCITY_LIMIT ACCEL={old_accel} SQUARE_CORNER_VELOCITY={old_sqv}`

You must do it via terminal etc. because of read-only access in your desired UI (Mainsail/Fluidd).

For @Frix-x would be nice, if you can change the macro accordingly of not already done :)

**Comment by Frix-x** [comment]
Hi there,

I think you've hit several things due to random incompatibilities in the versions of all these software.
So here is a summary:
- S&T v2.6.0 and v2.6.1 didn't change anything regarding Scipy. So I think a simple re-run of the install script would have installed it correctly. If you were upgrading from an older S&T version, it was a breaking change in S&T v2.5.0 from January 9th to re-run the install script to get the new dependencies installed, so this may be normal.
- S&T v2.6.0 was released on Feb 19th to account for a breaking change in Klipper. So if you are using this version of S&T or later, you will also need to update Klipper to a version after Feb 18th to get the features aligned.
- S&T v2.6.1 was also released 3 weeks ago to accommodate the accel_to_decel Klipper change in the same way. So if you have the latest S&T and a recent Klipper version, you should have no problem.

**Comment by Phil1988** [comment]
Thanks for your reply.

So S&T >v2.6.1 with latest klipper doesnt work because of the accel_to_decel changes.
S&T 2.6.1 would have worked with latest klipper if I had re-run the install script.
